version: '3.3'

services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    ports:
      - 5433:5432
    restart: unless-stopped
    volumes:
      - ./scripts/dumps/dump.sql:/docker-entrypoint-initdb.d/dump.sql
      - ./scripts/dumps:/dumps
    env_file:
      - ./scripts/env/database.dev.env

  backend:
    build: ./backend/
    image: tutor-backend
    container_name: backend
    depends_on:
      - postgres
    links:
      - postgres
    ports:
      - 8080:8080
    restart: unless-stopped
    volumes:
      - ./scripts/images:/images
      - ./scripts/load:/load
      - ./scripts/export:/export
    env_file:
      - ./scripts/env/backend.dev.env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/tutordb
 
  frontend:
    build:
      context:  ./frontend/
      dockerfile: Dockerfile
      args:
        NODE_ENV: dev
    image: tutor-frontend                                                     
    container_name: frontend
    depends_on:
      - backend
    links:
      - backend
    ports:
      - 8081:80
    restart: unless-stopped
    volumes:
      - ./scripts/localhost-nginx.conf:/etc/nginx/nginx.conf
      - ./scripts/error.log:/var/log/nginx/error.log
      - ./scripts/access.log:/var/log/nginx/access.log