name: build

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
       ref: courses
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Build with Maven
      run: mvn clean --file ./spring-api/pom.xml -Ptest test
    - name: Codecov
      uses: codecov/codecov-action@v1.0.5
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: ./spring-api/target/site/jacoco/jacoco.xml
        yml: ./spring-api/codecov.yml
